apiVersion: v1
kind: Service
metadata:
  labels:
    app: antares-client-api
    environment: Development
  name: antares-client-api
  namespace: antares
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: antares-client-api
  sessionAffinity: None
  type: ClusterIP
